### ISSUE TITLE
Specify that a field can be one of a list of options

### ISSUE THREAD

**Issue by eivindjahren** [equinor/configsuite#163]
Lets say you have the following kind of specification:

```yaml
vehicle_list:
  - spaceship:
      name: "Millenium Falcon"
      crew:
         - Han Solo
         - Chewbacca
  - time_machine:
     name: "The Dolorean"
     inventor: "Doc"
```

It would be nice to have a `OneOf` combinator to specify that the node matches one of  a known list of schemas:

```python
schema = {
    MK.Type: types.NamedDict,
    MK.Content: {
        "vehicles_list": {
            MK.Type: types.List,
            MK.Content: {
                MK.Item: MK.OneOf([
                     {MK.Type: types.NamedDict, Mk.Content: {"spaceship": {}},
                     {MK.Type: types.NamedDict, Mk.Content: {"time_machine": {}},
                ])
            }
        }
    }
}
```
This would also be handy for specifying that a field can be either a string or a float:

 ```python
MK.OneOf([{MK.Type: types.Float}, {MK:Type: types.String}])
```

**Comment by lars-petter-hauge** [comment]
Currently if this is needed a possible solution is to create validators that can check if the content is one of a set of items. But that does not work for containers of different structure, nor does it go well with documentation generation.

**Comment by markusdregi** [comment]
This will make the complexity of the data skyrocket and violate a design principle of `configsuite`, namely that all data fields are known up front. In other words, if `vehicle_list[0].spaceship` exists, then so should `vehicle_list[1].spaceship`. This complexity will in my opinion hit the programmer, but more importantly communication with the users.

I think the better solution in your concrete example would be to introduce a `(vehicle_)type` that can be either `spaceship` or `time_machine` and then implement specific validators for the two. If this turns out too complicated, then I think that is a clear hint that perhaps the users should not be exposed to a `vehicle_list`, but a `spaceship` and a `time_machine` list 🤷

**Comment by eivindjahren** [comment]
> all data fields are known up front [...] if `vehicle_list[0].spaceship` exists, then so should `vehicle_list[1].spaceship`.

I am not sure how to apply the design principle in terms of lists, but would it be correct to say "All lists must be homogenous"? 

> I think the better solution in your concrete example would be to introduce a `(vehicle_)type` that can be either `spaceship` or `time_machine` 

In this case the `vehicle_type` is the type `OneOf(Spaceship, TimeMachine)` and I get the job done. But there is no documentation of the fields of `Spaceship` and `TimemMachine`.

> then I think that is a clear hint that perhaps the users should not be exposed to a vehicle_list, but a spaceship and a time_machine list 

Its less logical when the list contains elements that naturally go together:

```yaml
coctail:
   - rum
     brand: "Havanah Club"
     proof: 60 # percent
   - milk:
     fat_content: 1 # percent
```
In this case it would be a bit silly to have a list for each ingredient type. You could make a homogenous list of tagged unions:

```yaml
coctail:
   - ingredient:
       type: "rum"
       brand: "Havanah Club"
       proof: 60 # percent
   - ingredient:
     type: "milk"
     fat_content: 1 # percent
```

And make a context validator that checks which fields should be present based on type. This becomes very cumbersome as the number of ingredient types increases, and there is no guidance from the generated documentation about which fields are required for which types.

**Comment by markusdregi** [comment]
> I am not sure how to apply the design principle in terms of lists, but would it be correct to say "All lists must be homogenous"?

All containers of arbitrary size needs to be homogenous. List elements must be homogenous. Furthermore, the keys in a dict must be homogenous and the dict values must be homogenous. It is only the named dicts, where you specify both all the keys and which type each of them maps to up front, that allows for different types within the same structure :)

**Comment by markusdregi** [comment]
I think the idea of deferring the documentation to the type is probably a good idea 👍 But as you say, transformations, defaulting etc will be difficult with the multi-type suggestion of this issue 🤷

**Comment by markusdregi** [comment]
In the `cocktail` example I'm not sure how much you expect to know up front about the ingredients. If there are certain elements you expect to be present for each of them and some that are arbitrary metadata you can do:

```yaml
coctail:
   -
     category: rum
     brand: "Havana Club"
     fraction: 0.5
  -
    category: milk
    brand: Happy Cow
    fraction: 0.5
    additional_info:
      fat_content: 1 # percent
      kind: "bovine"
```

Where you can add validators about certain types of `additional_info` to be present for various categories if you want to.

I also notice that you have a strong preference for making the list elements into a dictionary where the first level is a single key representing one of the data elements, like:

```yaml
   - rum:
       brand: "Havana Club"
       fraction: 0.5
```

I would find it really interesting if your users find that easier to read then the above `category` example. However, notice also that a layered transformation can be used to completely transform the data layout. But, the complexity goes up of course :)
